name: NotesVault CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
        mongodb-version: [5.0]

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package.json
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.8.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    
    - name: Install dependencies
      run: |
        cd backend
        npm install
        npm install --no-save node-fetch
    
    - name: Run tests
      run: |
        cd backend
        npm test

  frontend-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package.json
    
    - name: Install dependencies
      run: |
        cd frontend
        npm install
    
    - name: Run linting and tests
      run: |
        cd frontend
        CI=true npm test -- --passWithNoTests
